### ISSUE TITLE
Offboarding Checklist: Rebecca Hession

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#107]
ICPI Offboarding Checklist
--
The purpose of this checklist is to assist departing staff in transitioning out of their ICPI position. The below items will be completed by the departing staff member, supervisor, and ICPI coordination office.

**Name**: Rebecca Hession
**Agency:** State

Administrative Checklist
--
### Last two weeks:

**To be completed by Coordination Office:**
- [x] Inform OGAC HR of upcoming staff departure

**To be completed by departing staff:**
- [x] Schedule offboarding meeting with OGAC HR
- [x] Inform Colleagues of upcoming departure (send emails to groups you are a part of)
- [x] Develop transition plan/offboarding notes and share with Supervisor, Coordination Office, and POCs (where appropriate)

### Last week
**To be completed by departing staff:**
- [x] Meet with OGAC HR to return lobby key fob and State badge (if necessary)
- [x] Upload projects to SharePoint 
- [x] Transition interagency projects to another interagency colleague 

**To be completed by Coordination Office:**
- [x] Announce at inbrief 
- [x] Insert notice in senior staff notes
- [ ] Inform OGAC POCs 

### Last Day:

**To be completed by Coordination Office:**
- [ ] Update OGAC and other POCs
    - remind cluster POCs to update inbrief slides
    - remind Clusters/ECT/COOP/ST3, etc members to remove departing staff from distribution lists
- [x] Update relevant Listservs
- [ ] Update relevant meeting invites

**To be completed by Departing Staff:**
- [x] Return Badge, FOB, and RSA Token (if issued)
- [x] Complete agency specific offboarding of equipment and projects
      - return computer, badge, equipment, etc. 

**Documents**
- [x] Update ICPI Bio document
- [x] Update ICPI Emergency Contact List
- [x] Update ICPI Seating Chart
- [x] Update ICPI Org Chart

**Systems**
- [ ] Remove departing staff from ICPI SharePoint
- [ ] Remove departing staff from Panorama
- [ ] Remove departing staff from Analytic Workspaces
- [ ] Remove departing staff from DATIM
