### ISSUE TITLE
Onboarding Checklist: Miriam Hartig - USAID

### ISSUE THREAD

**Issue by cnichols3h** [ICPI/Coordination#114]
**ICPI Onboarding Checklist**
The purpose of this checklist is to assist new staff in getting set up at ICPI. The below items will be completed by the new staff member, Agency ICPI Leads, and ICPI coordination office.

Name: Miriam Hartig
Agency: USAID

**Administrative Checklist**
To be completed by new staff:
- [x]  Email Staff Bio to icpi@state.gov
- [x]  Email emergency contact information
(phone number, birthday, Emergency POC, relationship to Emergency POC, Emergency POC phone number) to icpi@state.gov

**Slack and Github**
- [x]  Sign Up for Slack https://slack.com/ and confirm via email to icpi@state.gov
(https://github.com/ICPI/Coordination/files/2933524/BLANK_PEPFAR.NDA.Form.2018.pdf) and email completed for to ICPI@state.gov
Time: 2 mins
Once you have an account, click on this link and you will have access to the ICPI slack organization and channels. Please review channels to join.
- [x]  Accept Slack Invitation
- [x]  Sign up for GitHub https://github.com/ (display full name in profile and set up 2 factor authentication) and email your username to icpi@state.gov
Time: 5 minutes.
https://github.com/
Once you have a username, we will invite you to the organization. You will then confirm your access in a ticket. Kindly complete the below actions and send an email once complete
GitHub Steps:
1. Electronically Sign Attached NDA & email it to ICPI@state.gov
2. Create GitHub Account & email username to ICPI@state
3. Update your Profile Name in your GitHub Settings (example below)
a. Add your full name to your profile in settings – a snapshot is below
b. Don’t forget to hit “update profile”
c. Once you have done this, kindly respond to me via email so I can mark it in our spreadsheet.
4. Two Factor Authentication in GitHub Settings (example below)
a. Click on settings and set up 2 factor authentication
b. Have your cell phone handy
- [x]  Complete - PEPFAR NDA form
- [x]  Accept GitHub Invitation

Examples:
Profile Name & How to set up 2-factor authentication
![62886991-4b2be000-bd0a-11e9-9e6f-9f239ea78831](https://user-images.githubusercontent.com/33493594/79139812-fa7ef200-7d84-11ea-970a-7512936a798d.png)

**To be completed by Coordination Office:**
- [x]  Add to Slack channel
- [x]  Add to GitHub
- [ ]  Supply office supplies (as applicable, with assistance from Agency)
- [ ]  Send email to OGAC HR alerting them that a new staff member is starting and that the agency lead will set up a time for the new staff member to meet with HR (CC leads)

**To be completed by new staff:**
- [ ]  Complete analyst skill survey (here) and email to icpi@state.gov

**To be completed by Agency:**
- [ ]  Liaise with Front Office to assign lobby key fob / MOU
- [ ]  Set up monitor (if applicable)
- [ ]  Set up agency email address, email icpi@state.gov

**To be completed by Coordination Office:**
- [ ] Send welcome email with bio to ICPI analysts and leads
- [ ]  Forward welcome email to OGAC
- [ ]  Update seating chart (if applicable)
- [ ]  Send seating chart to OGAC (if applicable)

**To be completed by new staff:**
- [x]  Set up Panorama account
- [x]  Set up SharePoint account
- [x]  Set up DATIM account

**Attend Cluster and Team Meetings:**
- [x]  Attend ICPI Inbrief on Mondays @10am
- [x]  Meet with team leads of the respective Cluster you will join / join the Cluster meetings

**To be completed by Coordination Office:**
- [ ]  Add new staff as member/power user on SharePoint
- [ ]  Add new staff to relevant listservs
- [ ]  Add new staff to relevant meeting invites
request access to Analytic workspaces (PAWS) https://github.com/ICPI/DIV/issues/140

**Training and Orientation**
**To be completed by new staff, Agency ICPI Lead:**
- [ ]  Attend ICPI Onboarding Training

If no to the above (due to timing), indicate that the new hire has been oriented to the following:

**Introduction to ICPI and Interagency Space and OGAC**
- [ ]  Complete the ICPI Onboarding training on the PEPFAR Virtual Academy (PVA):
learn.pepfar.net
- [ ]  ICPI Product overview / ICPI Huddle
- [ ]  DATIM
- [ ]  PEPFAR Panorama
- [ ]  Panorama Analytic Workspaces (PAW)
- [ ]  GitHub, ICPI page
- [ ]  Slack, ICPI
- [ ]  PEPFAR SharePoint
- [ ]  ICPI Calendar (on SP)
- [ ]  Conference room reservation (general and North America on SP)

**Additional training topics, as needed:**
- [ ]  MER Guidance
- [ ]  COP Guidance
- [ ]  Data Streams (MER, SIMS, EA, Budget)
