### ISSUE TITLE
Onboarding Checklist: {Staff Name}

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#53]
**First Day**:
To be completed by new staff:
- [ ] Email Staff Bio to icpi@state.gov
- [ ] Email emergency contact information (phone number, birthday, Emergency POC, relationship to Emergency POC, Emergency POC phone number) to icpi@state.gov

To be completed by Coordination Office:
- [ ] Liaise with Front Office to assign lobby key fob

**First Week**:
To be completed by new staff:

To be completed by Coordination Office:

**First Month**:
To be completed by new staff:

To be completed by Coordination Office:

**Comment by jb3436** [comment]
@hessionra I added a section on setting up meetings with team leads in the first month.

**Comment by jb3436** [comment]
Added PVA and Workspaces to the list
