### ISSUE TITLE
Offboarding Checklist: {Staff Name}

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#54]
ICPI Offboarding Checklist
--
The purpose of this checklist is to assist departing staff in transitioning out of their ICPI position. The below items will be completed by the departing staff member, supervisor, and ICPI coordination office.

**Name**: [ Insert Staff Member Name]
**Agency:** [ Insert Agency]

Administrative Checklist
--
### Last two weeks:

**To be completed by Coordination Office:**
- [ ] Inform OGAC HR of upcoming staff departure

**To be completed by departing staff:**
- [ ] Schedule offboarding meeting with OGAC HR

### Last week
**To be completed by departing staff:**
- [ ] Meet with OGAC HR to return lobby key fob and State badge (if necessary)

### Last Day:

**To be completed by Coordination Office:**
- [ ] Update relevant Listservs
- [ ] Update relevant meeting invites
- [ ] Update ICPI Bio document
- [ ] Update ICPI Emergency Contact List
- [ ] Update ICPI Seating Chart
- [ ] Remove departing staff from ICPI SharePoint
- [ ] Remove departing staff from GitHub
- [ ] Remove departing staff from Slack
