### ISSUE TITLE
Onboarding Checklist: Jenny Hurst

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#55]
ICPI Onboarding Checklist
--
The purpose of this checklist is to assist new staff in getting set up in the ICPI systems. The below items will be completed by the new staff member, supervisor, and ICPI coordination office.

**Name**: Jenny Hurst
**Agency:** Peace Corps

Administrative Checklist
--
### First Day:
**To be completed by new staff:**
- [x] Email Staff Bio to icpi@state.gov
- [x] Email emergency contact information 
    (phone number, birthday, Emergency POC, relationship to Emergency POC, Emergency POC phone number) to icpi@state.gov
- [x] Sign up for GitHub https://github.com/ (display full name in profile and set up 2 factor authentication) and email your username to icpi@state.gov
- [x] Sign Up for Slack  https://slack.com/ and confirm via email to icpi@state.gov
- [x] Complete [PEPFAR NDA Form 2018.pdf](https://github.com/ICPI/Coordination/files/2933524/BLANK_PEPFAR.NDA.Form.2018.pdf) and email  completed for to ICPI@state.gov
- [x] Accept GitHub Invitation
- [x] Accept Slack Invitation

**To be completed by Coordination Office:**
- [x] Add to Slack channel
- [x] Add to GitHub
- [x] Supply office supplies (_with assistance from Agency, if needed_)

### First Week:
**To be completed by new staff:**
- [x] Complete [analyst skill survey (here)](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Management%20and%20Processes/ICPI%20Analyst%20Assessment%20Survey_FINAL.xlsx) and email to icpi@state.gov

**To be completed by Agency:**
- [ ] Liaise with Front Office to assign lobby key fob
- [ ] Liaise with Front Office to assign State Badge
- [x] Set up internet connection
- [x] Set up printer/copier connection
- [x] Set up agency email address, email icpi@state.gov

**To be completed by Coordination Office:**
- [x] Send welcome email with bio to ICPI analysts and leads
- [x] Update seating chart

### First Month:
**To be completed by new staff:**
- [x] Set up [Panorama](www.pepfar-panorama.org) account 
- [x] Set up [SharePoint](https://pepfar.zendesk.com/hc/en-us) account
- [x] Set up [DATIM ](datim.org)account

**To be completed by Coordination Office:**
- [x] Add new staff as member/power user on SharePoint
- [x] Add new staff to relevant listservs
- [x] Add new staff to relevant meeting invites

Training and Orientation 
--

**To be completed by new staff, supervisor, and training partner**
- [x] Introduction to ICPI
- [x] DATIM
- [x] Panorama
- [x] Excel Tools
- [x] GitHub
- [x] Slack

_The following to be covered if there is no ICPI Onboarding scheduled around time of staff start date_
- [x] Analytic Datasets (MER, EA, SIMS, Budget)
- [x] MER Guidance
- [x] COP Guidance
- [x] Data calendars/schedules
- [x] ICPI overview
- [x] ICPI Product overview
- [x] Huddle
- [x] Inbrief
- [ ] GIS (_if applicable_)
- [x] Conference room reservation

**Comment by jleehurst** [comment]
@kimisatoPC and I walked through the checklist.  I have not completed the badge and key fob from State, and I do not have a state email address. I am in the process of completing the online DATIM training modules.
