### ISSUE TITLE
Offboarding Checklist: Dereje Tesfaye

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#56]
ICPI Offboarding Checklist
--
The purpose of this checklist is to assist departing staff in transitioning out of their ICPI position. The below items will be completed by the departing staff member, supervisor, and ICPI coordination office.

**Name**:Dereje Tessfaye
**Agency:** CDC

Administrative Checklist
--
### Last two weeks:

**To be completed by Coordination Office:**
- [x] Inform OGAC HR of upcoming staff departure

**To be completed by departing staff:**
- [x] Schedule offboarding meeting with OGAC HR

### Last week
**To be completed by departing staff:**
- [x] Meet with OGAC HR to return lobby key fob and State badge (if necessary)
- [ ] Upload projects to SharePoint 
- [ ] Transition interagency projects to another interagency colleague 

**To be completed by Coordination Office:**
- [x] Announce at inbrief 

### Last Day:

**To be completed by Coordination Office:**
- [ ] Update OGAC and other POCs
    - remind cluster POCs to update inbrief slides
    - remind Clusters/ECT/COOP/ST3, etc members to remove departing staff from distribution lists
- [x] Update relevant Listservs
- [x] Update relevant meeting invites

**Documents**
- [x] Update ICPI Bio document
- [x] Update ICPI Emergency Contact List
- [x] Update ICPI Seating Chart
- [ ] Update ICPI Org Chart

**Systems**
- [x] Remove departing staff from ICPI SharePoint
- [ ] Remove departing staff from Panorama
- [ ] Remove departing staff from DATIM
- [x] Remove departing staff from GitHub (email OGAC to remove from DATIM GH)
- [x] Remove departing staff from Slack

**Comment by kkale25** [comment]
@shazadahmed10  - can you please take a look at the above checklist and update anything I may have missed?

Thanks

**Comment by shazadahmed10** [comment]
@kkale25 this looks comprehensive..the only thing I can think of is deleting some more PEPFAR accounts (DATIM, Pano)

**Comment by kkale25** [comment]
@shazadahmed10  thanks Shazad. Can you take a look at some of the items under "to be completed by departing staff" and check them off (if appropriate)? I'm wondering specifically if there were any projects/documents that he created that should be uploaded to SP or other spaces?
