### ISSUE TITLE
Onboarding Checklist (P/T): Roma Bhatkoti 

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#57]
ICPI Modified Onboarding Checklist
--
The purpose of this modified checklist is to assist new staff in getting set up in the ICPI systems. We have included items relevant to Roma, as she will be frequently visiting ICPI. The below items will be completed by the new staff member, supervisor, and ICPI coordination office.

**Name**:  Roma
**Agency:** CDC - based in Atlanta - Part Time (PT) at ICPI DC

Administrative Checklist
--
### First Day:
**To be completed by new staff:**
- [x] Email Staff Bio to icpi@state.gov
- [x] Email emergency contact information 
    (phone number, birthday, Emergency POC, relationship to Emergency POC, Emergency POC phone number) to icpi@state.gov
- [x] Sign up for GitHub https://github.com/ (display full name in profile and set up 2 factor authentication) and email your username to icpi@state.gov
- [x] Sign Up for Slack  https://slack.com/ and confirm via email to icpi@state.gov
- [x] Complete [PEPFAR NDA Form 2018.pdf](https://github.com/ICPI/Coordination/files/2933524/BLANK_PEPFAR.NDA.Form.2018.pdf) and email  completed for to ICPI@state.gov
- [x] Accept GitHub Invitation
- [x] Accept Slack Invitation

**To be completed by Coordination Office:**
- [x] Add to Slack channel
- [x] Add to GitHub
- [ ] Supply office supplies (_with assistance from Agency, if needed_)

### First Week:
**To be completed by new staff:**
- [ ] Complete [analyst skill survey (here)](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Management%20and%20Processes/ICPI%20Analyst%20Assessment%20Survey_FINAL.xlsx) and email to icpi@state.gov

**To be completed by Coordination Office:**
- [ ] Send welcome email with bio to ICPI analysts and leads

### First Month:
**To be completed by new staff:**
- [x] Set up [Panorama](www.pepfar-panorama.org) account 
- [x] Set up [SharePoint](https://pepfar.zendesk.com/hc/en-us) account
- [x] Set up [DATIM ](datim.org)account
- [x] Attend Cluster and Team Meetings (ask ICPI to forward)
- [x] Meet with team leads of the coordination Cluster teams (to get oriented to workflows)
    use ICPI master contact list ([click here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCommunications%2FMaster%20ICPI%20Contact%20List&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)) to reach out to the below individuals or ask your onboarding liaison for email addresses. 
    - [ ] ICPI Coordinator
    - [ ] OCM Team Leads 
    - [ ] ICEE Team Lead
    - [ ] DAQ Team Lead
    - [ ] DIV Team Lead

**To be completed by Coordination Office:**
- [x] Add new staff as member/power user on SharePoint
- [x] Add new staff to relevant listservs
- [x] Add new staff to relevant meeting invites

Training and Orientation 
--
_The following to be covered if there is no ICPI Onboarding scheduled around time of staff start date_
- [x] COP Guidance
- [x] Data calendars/schedules
- [x] ICPI overview
- [x] ICPI Product overview
- [x] Huddle
- [ ] Conference room reservation
