### ISSUE TITLE
Offboarding Checklist: Katya Noykhovich

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#59]
ICPI Offboarding Checklist
--
The purpose of this checklist is to assist departing staff in transitioning out of their ICPI position. The below items will be completed by the departing staff member, supervisor, and ICPI coordination office.

**Name**: Katya Noykhovich
**Agency:** Peace Corps

Administrative Checklist
--
### Last two weeks:

**To be completed by Coordination Office:**
- [x] Inform OGAC HR of upcoming staff departure

**To be completed by departing staff:**
- [x] Schedule offboarding meeting with OGAC HR
- [x] Inform Colleagues of upcoming departure
- [x] Develop transition plan and share with Supervisor, Coordination Office, and POCs (where appropriate)

### Last week
**To be completed by departing staff:**
- [x] Meet with OGAC HR to return lobby key fob and State badge (if necessary)
- [x] Upload projects to SharePoint 
- [x] Transition interagency projects to another interagency colleague 

**To be completed by Coordination Office:**
- [x] Announce at inbrief 
- [x] Insert notice in senior staff notes
- [x] Inform OGAC POCs 

### Last Day:

**To be completed by Coordination Office:**
- [x] Update OGAC and other POCs
    - remind cluster POCs to update inbrief slides
    - remind Clusters/ECT/COOP/ST3, etc members to remove departing staff from distribution lists
- [x] Update relevant Listservs
- [x] Update relevant meeting invites

**Documents**
- [x] Update ICPI Bio document
- [x] Update ICPI Emergency Contact List
- [x] Update ICPI Seating Chart
- [x] Update ICPI Org Chart

**Systems**
- [x] Remove departing staff from ICPI SharePoint
- [x] Remove departing staff from Panorama
- [x] Remove departing staff from Analytic Workspaces
- [x] Remove departing staff from DATIM
- [x] Remove departing staff from GitHub (email OGAC to remove from DATIM GH)
- [x] Remove departing staff from Slack
