### ISSUE TITLE
Offboarding Checklist: Faith Fawale

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#65]
ICPI Offboarding Checklist
--
The purpose of this checklist is to assist departing staff in transitioning out of their ICPI position. The below items will be completed by the departing staff member, supervisor, and ICPI coordination office.

**Name**: Faith Fawale
**Agency:** CDC/GDIT

Administrative Checklist
--

**To be completed by Coordination Office:**
- [x] Inform OGAC HR of staff departure

**To be completed by departing staff:**
- [ ] Schedule offboarding meeting with OGAC HR
- [x] Inform Colleagues of upcoming departure
- [ ] Develop transition plan and share with Supervisor, Coordination Office, and POCs (where appropriate)

- [x] Staff turned in badge and Fob to colleague. Agency lead turned in Badge and fob to OGAC HR. OGAC confirmed receipt. 

### Last week
**To be completed by departing staff:**
- [ ] Meet with OGAC HR to return lobby key fob and State badge (if one was issued)
- [ ] Upload projects to SharePoint 
- [ ] Transition interagency projects to another interagency colleague 

**To be completed by Coordination Office:**
- [x] Announce at inbrief 
- [ ] Insert notice in senior staff notes
- [x] Inform OGAC POCs 

### Last Day:

**To be completed by Coordination Office:**
- [x] Update OGAC and other POCs
    - remind cluster POCs to update inbrief slides
    - remind Clusters/ECT/COOP/ST3, etc members to remove departing staff from distribution lists
- [x] Update relevant Listservs
- [x] Update relevant meeting invites

**Documents**
- [x] Update ICPI Bio document
- [x] Update ICPI Emergency Contact List
- [x] Update ICPI Seating Chart
- [x] Update ICPI Org Chart

**Systems**
- [x] Remove departing staff from ICPI SharePoint
- [x] Remove departing staff from Panorama
- [x] Remove departing staff from Analytic Workspaces
- [x] Remove departing staff from DATIM
- [x] Remove departing staff from GitHub (email OGAC to remove from DATIM GH)
- [x] Remove departing staff from Slack

**Comment by hessionra** [comment]
@anu87 @jb3436 please let me know if you would like me to notify HR of Faith's departure or if @jb3436 or JP would rather email them!

**Comment by jb3436** [comment]
HR Notified
Badge and Fob turned in - confirmation email received from ogac HR.
