### ISSUE TITLE
Onboarding Checklist: Lachandra Spencer

### ISSUE THREAD

**Issue by hessionra** [ICPI/Coordination#66]
ICPI Onboarding Checklist
--
The purpose of this checklist is to assist new staff in getting set up in the ICPI systems. The below items will be completed by the new staff member, supervisor, and ICPI coordination office.

**Name**: Lachandra Spencer
**Agency:** CDC/GDIT

Administrative Checklist
--
### First Day:
**To be completed by new staff:**
- [x] Email Staff Bio to icpi@state.gov
- [x] Email emergency contact information 
    (phone number, birthday, Emergency POC, relationship to Emergency POC, Emergency POC phone number) to icpi@state.gov
- [x] Sign up for GitHub https://github.com/ (display full name in profile and set up 2 factor authentication) and email your username to icpi@state.gov
- [x] Sign Up for Slack  https://slack.com/ and confirm via email to icpi@state.gov
- [x] Complete [PEPFAR NDA Form 2018.pdf](https://github.com/ICPI/Coordination/files/2933524/BLANK_PEPFAR.NDA.Form.2018.pdf) and email  completed for to ICPI@state.gov
- [x] Accept GitHub Invitation
- [x] Accept Slack Invitation

**To be completed by Coordination Office:**
- [x] Add to Slack channel
- [x] Add to GitHub
- [x] Supply office supplies (_with assistance from Agency, if needed_)

### First Week:
**To be completed by new staff:**
- [x] Complete [analyst skill survey (here)](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Management%20and%20Processes/ICPI%20Analyst%20Assessment%20Survey_FINAL.xlsx) and email to icpi@state.gov

**To be completed by Agency:**
- [ ] Liaise with Front Office to assign lobby key fob
- [ ] Liaise with Front Office to assign State Badge
- [ ] Set up internet connection
- [ ] Set up printer/copier connection
- [x] Set up agency email address, email icpi@state.gov

**To be completed by Coordination Office:**
- [x] Send welcome email with bio to ICPI analysts and leads
- [ ] Update seating chart

### First Month:
**To be completed by new staff:**
- [x] Set up [Panorama](www.pepfar-panorama.org) account 
- [x] Set up [SharePoint](https://pepfar.zendesk.com/hc/en-us) account
- [x] Set up [DATIM ](datim.org)account (signed up but waiting for account approval)
- [ ] Attend Cluster and Team Meetings (ask ICPI to forward)
- [ KP, DAQ, met with Rebecca] 

- [ ] Meet with team leads of the coordination Cluster teams (to get oriented to workflows)
    use ICPI master contact list ([click here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCommunications%2FMaster%20ICPI%20Contact%20List&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)) to reach out to the below individuals or ask your onboarding liaison for email addresses. 
    - [ ] ICPI Coordinator
    - [x] OCM Team Leads 
    - [ ] ICEE Team Lead
    - [x] DAQ Team Lead
    - [ ] DIV Team Lead

**To be completed by Coordination Office:**
- [ ] Add new staff as member/power user on SharePoint
- [ ] Add new staff to relevant listservs
- [ ] Add new staff to relevant meeting invites

Training and Orientation 
--

**To be completed by new staff, supervisor, and training partner**
- [x] Introduction to ICPI
- [x] Sharepoint
- [x] DATIM
- [x] Panorama
- [x] Excel Tools
- [x] GitHub
- [x] Slack

_The following to be covered if there is no ICPI Onboarding scheduled around time of staff start date_
- [x] Analytic Datasets (MER, EA, SIMS, Budget)
- [x] MER Guidance
- [x] COP Guidance
- [x] Data calendars/schedules
- [x] ICPI overview
- [x] ICPI Product overview
- [x] Huddle
- [x] Inbrief
- [ ] GIS (_if applicable_)
- [x] Conference room reservation

**Comment by shazadahmed10** [comment]
Since the new GIS analyst will be starting as soon as next week (6/17), I think cluster meetings and meeting team leads can happen for LaChandra and the new person at the same time. 
Furthermore, the new GIS analyst will need their own onboarding training, and LaChandra should sit in those to reinforce what she learned at the ICPI on-boarding. Thoughts?
