### ISSUE TITLE
Offboarding Checklist: Catherine Gulley 

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#85]
ICPI Offboarding Checklist for ICPI Intern
--
The purpose of this checklist is to assist departing staff in transitioning out of their ICPI position. The below items will be completed by the departing staff member, supervisor, and ICPI coordination office.

**Name**: Catherine Gulley
**Agency:** Peace Corps 
#68 (onboarding checklist)

Administrative Checklist
--
### Last two weeks:

**To be completed by Coordination Office:**
- [x] Inform OGAC HR of upcoming staff departure

**To be completed by departing staff:**
- [x] Inform Colleagues of upcoming departure
- [x] Develop transition plan/offboarding notes and share with Supervisor, Coordination Office, and POCs (where appropriate)

### Last week
**To be completed by departing staff:**
- [x] Upload projects to SharePoint 
- [x] Transition interagency projects to another interagency colleague 

**To be completed by Coordination Office:**
- [x] Announce at inbrief 
- [x] Inform OGAC POCs 

### Last Day:

**To be completed by Coordination Office:**
- [x] Update OGAC and other POCs
    - remind cluster POCs to update inbrief slides
    - remind Clusters/ECT/COOP/ST3, etc members to remove departing staff from distribution lists
- [x] Update relevant Listservs
- [x] Update relevant meeting invites
- [x] Email Peace Corps and ask for CG to be transferred from OGHH to OHS  - do not deactivate profile 

**To be completed by Departing Staff:**
- [x] Return Badge, FOB, and RSA Token (if issued)
- [x] Complete agency specific offboarding of equipment and projects
      - return computer, badge, equipment, etc. 

**Documents**
- [x] Update ICPI Bio document
- [x] Update ICPI Emergency Contact List
- [x] Update ICPI Seating Chart
- [x] Update ICPI Org Chart

**Systems**
- [x] Remove departing staff from ICPI SharePoint
- [x] Remove departing staff from Panorama
- [x] Remove departing staff from GitHub
- [x] Remove departing staff from Slack
