### ISSUE TITLE
Coordinator Coverage 8/26-9/6

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#90]
Coverage List
--

- [x] Informed OGAC POCs of Leave.   8/23
Systems (Mark D., DataStrong, Systems Training, Data Management, Shabeen, Kelling, Irum, Bryan A., Blander) 
- [x] Informed ICPI Leads and Cluster Leads 8/23
- [x] Out of office on

### Light coverage - no major projects or deadlines while JB is out.

8/26 (Mon) Facilitate/Moderat ICPI Inbrief (keep to time) & Nigeria TDY Presentation (keep to time) @cnichols3h 
8/27 (Tues) PRIME Systems and Training Team Meeting - Share ICPI plans @jleehurst   
8/28 (Wed) Data Management Call - Submit agenda items to Will & Follow Up on items after @jaliasd @shazadahmed10 @HoustonJamie 
8/29 (Thurs) PRIME Systems Review (Team Leads Meeting) **_Jasmine to call in_**  
**_9/2 HOLIDAY_**
9/3 (Tues) PRIME Systems and Training Team Meeting @jleehurst to cover if needed
9/4 (Wed) Data Management Call - Submit agenda items to Will & Follow Up on items after  @jaliasd @shazadahmed10 @HoustonJamie 
9/5 (Thurs) PRIME Systems Review (Team Leads Meeting) @HoustonJamie **_Jasmine to call in_**  

### Action Items:
- [x]  Monitor Product Updates & Huddle Release (9/3) @hessionra @cnichols3h @HoustonJamie 
- [ ] Set Date for OGAC ICPI Leadership Retreat - Late September --> Find Date & Send Save the date https://github.com/ICPI/Coordination/issues/88 @hessionra @cnichols3h @HoustonJamie 
- [x] Review SI COOP for FIeld and HQ https://github.com/ICPI/Coordination/issues/80 @jleehurst to resend to leads and request review by a certain date. 
- [x] Update Staffing LOE document with ALL agencies @hessionra https://github.com/ICPI/Coordination/issues/89
- [ ] Update GitHub ticket with location of updated LOE documents once done https://github.com/ICPI/Coordination/issues/89 @hessionra 
- [x] India TDY Follow Up https://github.com/ICPI/OCM/issues/15 @jleehurst 
     - send email notification to leads (done)
     - meet with Jackson to discuss potential content
     - identify a POC (s) to deliver content based on topics discussed with Jackson
Onboarding Training next steps 1. PVA Content and Recordings and Course and 2. in person portion in October @jleehurst 

### Keep an Eye on
- GitHub Management of Issues
- Slack Channel Discussions
- ECT follow up conversations
- COOP follow up discussions
- Panorama Q4 leadership discussions
- DHIS2 Developer - Lars at SGAC @cnichols3h 

### Reminders
- Inbrief and Leads Cancelled 9/2
- Huddle delayed due to Genie and MSD delay
- DHIS2 Developer on Site
- Jamie back from leave Tuesday 8/27
