### ISSUE TITLE
Coordinator Coverage 5/27-5/31

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#91]
Coordinator Coverage Notes
--
Submitted this ticket after the fact for consistency and documentation

See below for info sent to leads and senior ICPI staff
_________

Dear ICPI Leads

_Coordination Cluster Leads ccd for awareness (DAQ, DIV, OCM, ICEE)_

Below, please find my coverage notes. Thank you to Kashmira for agreeing to be the on-site acting coordinator!

I have flagged all of the below items in advance. I have noted the items that need more follow up and discussion.

**There are specific Items below for ,  **** Jamie ****,**** Katie O, **** **** Kashmira ****, **** Rebecca ****,**

**Rebecca**  will follow up with you all on the below items

**Meeting Facilitation Coverage &amp; Tasks**

- **PAW to Pano Discussion**   **Jamie/Katie O **** Kashmira**
  - Use existing dossiers as an example and move forward with pano process
  - FOLLOW UP: Please ask Jacob to lead discussion around process and next steps  **Jamie**
  - Projects to advance
     - 2nd 90
     - HRH
     - DREAMS (rebuild existing one)
     - Viral Load/3rd 90
    -  Review what is included in current clinical cascades and build off of that
     - Cervical Cancer
     - Review Checklist and Timeline and share with people before meeting on Thursday  **Jamie/Katie O **** Kashmira**

- **Facilitate Leads Meeting (Tuesday 5/28)**  **Kashmira**
- **Talking Points/Agenda**
     - Retreat
     - Agenda Review (draft attached)
      - Working sessions to be scheduled - keep in mind onboarding training
  - Timeline for Retreat review
  - Workplan development timeline
    - Friday - June 7
    - Review 6/10-6/11
    - Feedback by 6/12/13 at the latest
    - Final updates on the 20th - emphasize these in presentation
     - External Presenters
     - LOE Next Steps Discussion
     - Review cluster membership matrices
       - Pull names from cluster membership matrix into ICPI LOE template
      - Send to leads to review and update for ICPI overall LOE
         - Option A: Email remote individuals on the list ICPI leads submit to ask for their LOE
         - Option B: At retreat cluster and team leads will confirm with members, what the LOE on the specific cluster will be
    - Dossier next steps - make sure staff are prepped for Thursday - we will be doing
    - Debrief from Pano
    - KP Dashboard Approved - feedback sent
    - VMMC request
    - Finding Men Request
    - Inbrief  5/27 Cancelled

**Meeting Attendance Coverage:**

- **Whats new in Pano webinar (5/28) - ALL**
- **Data Management Meeting**  (Wed @ 10:00am) ( **Josh, **** Jamie, Shazad)**
- **PRIME Systems Training Meeting**  Tuesdays @ 10:00am  ( **Kashmira**  )
- **ECT Co-Leads Call**   ( **Wednesday 5/29**   from 4-5pm – invite forwarded)  **Kashmira**

**Tasks (due week of 5/28)**

- Update retreat invite from 1 to 2 days and include a rough shell of the agenda  **Rebecca**
- Put special placehodler on Irum&#39;s calendar to do welcome session on day 1 of retreat  **Rebecca**
- Send invite to Irum, Kelling, Ebonnie, Mark, Tiffany, Bill Paul, Jeff Blander, PPMs for opening session of retreat  **Rebecca**
- Finalize  Huddle **Rebecca (****5/28-29)**
- Send Unit summary on 5/28  **Rebecca**
- Review Huddle and Confirm it is ready to send  **Kashmira**
- Find a time to reschedule staff meeting   **Kashmira **** Rebecca**
- Make sure all tools uploaded have been &quot;approved&quot; on SP  **Rebecca**
- LOE Next Steps  **Rebecca ****  DUE 5/29**
  - Review cluster membership matrices
  - Pull names from cluster membership matrix into ICPI LOE template
  - Send to leads to review and update for ICPI overall LOE
  - Option A: Email  **remote**  individuals on the list ICPI leads submit to ask for their LOE
  - Option B: At retreat,  cluster and team leads will confirm with members, what the LOE on the specific cluster  will be
- Dev Con Preparation (if necessary)   **Kashmira**
- Finding Men Request  **Kashmira**
- VMMC Request  **Kashmira**
-    Additional Talking points for leads 5/28    **Kashmira**

**Keep an eye on:**

- PPM Training on new items in PAW
- ECT How to guide on using new pano visuals from an ECT, COOP perspective
- Analytic Workspaces training
- Workspaces Project - 2nd 90 (in office POC = Nicole)
- Workspaces Project - HSS (Travis POC)
- Engagement requests
- Onboarding training

**Reminders**

Inbrief  cancelled 5/28

**FYI**

Jasmine sent note of OOO to systems, PRIME,  OGAC, Systems,

**Comment by jb3436** [comment]
Feedback on Documents and Status
-
- [ ] [Agenda ICPI Retreat June 2019_05242019.xlsx](https://github.com/ICPI/Coordination/files/3536321/Agenda.ICPI.Retreat.June.2019_05242019.xlsx)
- [ ] [Agenda Themes and Notes - Retreat June 2019 _05242019.docx](https://github.com/ICPI/Coordination/files/3536322/Agenda.Themes.and.Notes.-.Retreat.June.2019._05242019.docx)
- [x] [Dossier Workplan and CheckList May232019.docx](https://github.com/ICPI/Coordination/files/3536323/Dossier.Workplan.and.CheckList.May232019.docx)
