### ISSUE TITLE
Onboarding Checklist: Maddy Schneider

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#92]
ICPI Onboarding Checklist
--
The purpose of this checklist is to assist new staff in getting set up in the ICPI systems. The below items will be completed by the new staff member, supervisor, and ICPI coordination office.

**Name**:  Maddy Schneider
**Agency:** USAID

Administrative Checklist
--
### First Day:
**To be completed by new staff:**
- [x] Email Staff Bio to icpi@state.gov
- [x] Email emergency contact information 
    (phone number, birthday, Emergency POC, relationship to Emergency POC, Emergency POC phone number) to icpi@state.gov

#### Slack and Github

- [x] Sign Up for Slack  https://slack.com/ and confirm via email to icpi@state.gov a
     Time: 2 mins
     Once you have an account, click on this link  and you will have access to the ICPI slack organization and channels. Please review channels to join. 
- [x] Accept Slack Invitation
- [x] Sign up for GitHub https://github.com/ (display full name in profile and set up 2 factor authentication) and email your username to icpi@state.gov
     Time: 5 minutes.
     https://github.com/
     Once you have a username, we will invite you to the organization. You will then confirm your access in a ticket. Kindly complete the below actions and send an email once complete 

**GitHub Steps:**
1.	Electronically Sign Attached NDA & email it  to ICPI@state.gov 
[BLANK_PEPFAR NDA Form 2018.pdf](https://github.com/ICPI/Coordination/files/3731708/BLANK_PEPFAR.NDA.Form.2018.pdf)
2.	Create GitHub Account & email username to ICPI@state
3.	Update your Profile Name in your GitHub Settings (example below) 
     a.	Add your full name to your profile in settings – a snapshot is below 
     b.	Don’t forget to hit “update profile”
     c.	Once you have done this, kindly respond to me via email so I can mark it in our spreadsheet. 

4.	Two Factor Authentication in GitHub Settings (example below) 
     a.	Click on settings and set up 2 factor authentication
     b.	Have your cell phone handy

- [x] Complete [PEPFAR NDA Form 2018.pdf](https://github.com/ICPI/Coordination/files/2933524/BLANK_PEPFAR.NDA.Form.2018.pdf)
- [x] Accept GitHub Invitation

Examples:
Profile Name & How to set up 2-factor authentication
 
![image](https://user-images.githubusercontent.com/13006198/62886991-4b2be000-bd0a-11e9-9e6f-9f239ea78831.png)

**To be completed by Coordination Office:**
- [x] Add to Slack channel
- [x] Add to GitHub
- [ ] Supply office supplies (_with assistance from Agency, if needed_)
- [ ] Send email to OGAC HR alerting them that a new staff member is starting and that the agency lead will set up a time for the new staff member to meet with HR (CC leads)

### First Week:
**To be completed by new staff:**
- [ ] Complete [analyst skill survey (here)](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Management%20and%20Processes/ICPI%20Analyst%20Assessment%20Survey_FINAL.xlsx) and email to icpi@state.gov

**To be completed by Agency:**
- [ ] Liaise with Front Office to assign lobby key fob
- [ ] Liaise with Front Office to assign State Badge
- [ ] Set up internet connection
- [ ] Set up printer/copier connection
- [ ] Set up agency email address, email icpi@state.gov

**To be completed by Coordination Office:**
- [ ] Send welcome email with bio to ICPI analysts and leads
- [ ] Forward welcome email to OGAC
- [ ] Update seating chart 
- [ ] Send seating chart to OGAC

### First Month:
**To be completed by new staff:**
- [x] Set up [Panorama](www.pepfar-panorama.org) account 
- [x] Set up [SharePoint](https://pepfar.zendesk.com/hc/en-us) account
- [x] Set up [DATIM ](datim.org)account
- [ ] Attend Cluster and Team Meetings (ask ICPI to forward)
- [ ] Meet with team leads of the coordination Cluster teams (to get oriented to workflows)
    use ICPI master contact list ([click here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCommunications%2FMaster%20ICPI%20Contact%20List&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)) to reach out to the below individuals or ask your onboarding liaison for email addresses. 
    - [ ] ICPI Coordinator
    - [ ] OCM Team Leads 
    - [ ] ICEE Team Lead
    - [ ] DAQ Team Lead
    - [ ] DIV Team Lead

**To be completed by Coordination Office:**
- [ ] Add new staff as member/power user on SharePoint
- [ ] Add new staff to relevant listservs
- [ ] Add new staff to relevant meeting invites
- [ ] request access to Analytic workspaces (PAWS) https://github.com/ICPI/DIV/issues/140 

Training and Orientation 
--

**To be completed by new staff, supervisor, and training partner**
- [ ] Introduction to ICPI and Interagency Space and OGAC
- [ ] ICPI Product overview
- [ ] DATIM
- [ ] Panorama
- [ ] Analytic Workspaces
- [ ] Excel Tools
- [ ] GitHub
- [x] Slack
- [ ] SharePoint
- [ ] ICPI Calendar (on SP)
- [ ] Conference room reservation (general and North America on SP)
- [x] PEPFAR Virtual Academy
- [x] Inbrief

_The following to be covered if there is no ICPI Onboarding scheduled around time of staff start date_

**Platform & Organization Orientation:**
- [ ] ICPI overview & review of Interagency
- [ ] ICPI Product overview
- [ ] Huddle

**Data & Guidance Orientation:**
- [ ] Analytic Datasets (MER, EA, SIMS, Budget)
- [x] MER Guidance
- [ ] COP Guidance
- [ ] Data calendars/schedules
- [ ] GIS (_if applicable_)

[BLANK_PEPFAR NDA Form 2018.pdf](https://github.com/ICPI/Coordination/files/3731708/BLANK_PEPFAR.NDA.Form.2018.pdf)

**Comment by jb3436** [comment]
@SchneiderMadeline please see above and complete the items and send them in via email so we can get you access to platforms asap.
