### ISSUE TITLE
Offboarding Checklist: Jasmine Buttolph 

### ISSUE THREAD

**Issue by jb3436** [ICPI/Coordination#93]
ICPI Offboarding Checklist
--
The purpose of this checklist is to assist departing staff in transitioning out of their ICPI position. The below items will be completed by the departing staff member, supervisor, and ICPI coordination office.

**Name**: [ Insert Staff Member Name]
**Agency:** [ Insert Agency]

Administrative Checklist
--
### Last two weeks:

**To be completed by Coordination Office:**
- [x] Inform OGAC HR of upcoming staff departure

**To be completed by departing staff:**
- [x] Schedule offboarding meeting with OGAC HR
- [x] Inform Colleagues of upcoming departure (send emails to groups you are a part of)
Emailed/Met with:
     - [x]  ICPI Leads
     - [x]  ICPI Staff
     - [x]  PRIME Staff
     - [x]  Data management team
     - [x]  Level 1 Systems Meeting
     - [x]  DATIM/Zendesk 
     - [x]  Panorama Team/DataStrong
     - [x]  SharePoint POCs
     - [x]  Program Quality (Shabeen, Melissa, Bill, Heather, Jenny, Caroline)
     - [x]  Systems Training Team 
     - [x]  SGAC Wellness Commtitee
     - [x]  Blander
     - [x]  Email Each Cluster/Team
     - [x]  SGAC_STAFF 

- [x] Develop transition plan/offboarding notes and share with Supervisor, Coordination Office, and POCs (where appropriate)

### Last week
**To be completed by departing staff:**
- [x] Meet with OGAC HR to return lobby key fob and State badge (if necessary)
- [x] Upload projects to SharePoint 
- [x] Transition interagency projects to another interagency colleague 

**To be completed by Coordination Office:**
- [x] Announce at inbrief 
- [x] Insert notice in senior staff notes
- [x] Inform OGAC POCs 

### Last Day:

**To be completed by Coordination Office:**
- [ ] Update OGAC and other POCs
    - remind cluster POCs to update inbrief slides
    - remind Clusters/ECT/COOP/ST3, etc members to remove departing staff from distribution lists
- [x] Update relevant Listservs
- [x] Update relevant meeting invites

**To be completed by Departing Staff:**
- [x] Return Badge, FOB, and RSA Token (if issued)
- [x] Complete agency specific offboarding of equipment and projects
      - return computer, badge, equipment, etc. 

**Documents**
- [x] Update ICPI Bio document
- [x] Update ICPI Emergency Contact List
- [x] Update ICPI Seating Chart
- [ ] Update ICPI Org Chart

**Systems**
- [x] Remove departing staff from ICPI SharePoint
- [x] Remove departing staff from Panorama
- [x] Remove departing staff from Analytic Workspaces
- [x] Remove departing staff from DATIM
- [x] Remove departing staff from GitHub (email OGAC to remove from DATIM GH)
- [x] Remove departing staff from Slack
